# Generate Data

## Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
import os
import time
#from operator import xor
#from blocks import Blocks
from worm_simulation import WormSimulation
from bonds import Bonds
from specific_heat import SpecificHeat
from pca import PrincipalComponent
#from iterated_blocking import *
#from count_bonds import *
from specific_heat import SpecificHeat
from count_bonds import *
import matplotlib.image as mpimg
from matplotlib.offsetbox import AnchoredText
import matplotlib.offsetbox as offsetbox

%autoreload 2
%matplotlib notebook
import matplotlib as mpl
label_size = 14
plt.rc('font', family='serif')
plt.rc('text', usetex=True)
mpl.rcParams['xtick.labelsize'] = label_size 
mpl.rcParams['ytick.labelsize'] = label_size 

Tc =  2./np.log(1+np.sqrt(2))    # critical temperature

In [2]:
bonds_temp_arr = np.arange(1., 3.5, 0.1)

bonds_temp_arr_fine = np.arange(1.8, 2.8, 0.05)

In [4]:
bonds_temp_arr_ = []
for i in bonds_temp_arr:
    bonds_temp_arr_.append(i)
for i in bonds_temp_arr_fine:
    if i not in bonds_temp_arr_:
        bonds_temp_arr_.append(i)

In [5]:
bonds_temp_arr_ = np.array(sorted(bonds_temp_arr_), dtype=np.float32)

bonds_temp_arr_ = np.unique(bonds_temp_arr_)

In [11]:
bonds_temp_arr_

bonds8_temp_arr = np.arange(2.1, 2.6, 0.01)
bonds4_temp_arr = np.arange(2.1, 2.8, 0.01)

bonds32_temp_arr = np.arange(2.1,2.4, 0.01)
bonds16_temp_arr = np.arange(2.1, 2.5, 0.01)

array([ 1.        ,  1.10000002,  1.20000005,  1.29999995,  1.39999998,
        1.5       ,  1.60000002,  1.70000005,  1.79999995,  1.85000002,
        1.89999998,  1.95000005,  2.        ,  2.04999995,  2.0999999 ,
        2.1500001 ,  2.20000005,  2.25      ,  2.29999995,  2.3499999 ,
        2.4000001 ,  2.45000005,  2.5       ,  2.54999995,  2.5999999 ,
        2.6500001 ,  2.70000005,  2.75      ,  2.79999995,  2.9000001 ,
        3.        ,  3.0999999 ,  3.20000005,  3.29999995,  3.4000001 ,
        3.5       ,  3.5999999 ], dtype=float32)

In [2]:
bonds_temp_arr0 = np.arange(1., 1.5, 0.1)
bonds_temp_arr1 = np.arange(1.5, 2., 0.1)
bonds_temp_arr2 = np.arange(2., 2.25, 0.05)
bonds_temp_arr3 = np.arange(2.25, 2.5, 0.05)
bonds_temp_arr4 = np.arange(2.5, 2.9, 0.1)
bonds_temp_arr5 = np.arange(2.9, 3.2, 0.1)
bonds_temp_arr6 = np.arange(3.2, 3.5, 0.1)

In [4]:
print(bonds_temp_arr0)
print(bonds_temp_arr1)
print(bonds_temp_arr2)
print(bonds_temp_arr3)
print(bonds_temp_arr4)
print(bonds_temp_arr5)
print(bonds_temp_arr6)

[ 1.   1.1  1.2  1.3  1.4]
[ 1.5  1.6  1.7  1.8  1.9]
[ 2.    2.05  2.1   2.15  2.2 ]
[ 2.25  2.3   2.35  2.4   2.45]
[ 2.5  2.6  2.7  2.8]
[ 2.9  3.   3.1  3.2]
[ 3.2  3.3  3.4]


In [3]:
sim64 = Bonds(64, run=True, num_steps=1E7, verbose=True, T_arr=bonds_temp_arr0[:2])

compilation -- start

compilation -- done

runs -- start

Running L = 64, T = 1.0, num_steps:10000000.0
Running L = 64, T = 1.1, num_steps:10000000.0
Saving configs to: ../data/configs/64_lattice/separated_data/64_config_1.0.txt
Saving configs to: ../data/configs/64_lattice/separated_data/64_config_1.1.txt
Saving blocked configs to: ../data/blocked_configs/64_lattice/double_bonds_0/64_config_1.0.txt
Saving blocked configs to: ../data/blocked_configs/64_lattice/double_bonds_0/64_config_1.1.txt


In [3]:
sim64 = Bonds(64, run=True, num_steps=1E7, verbose=True, T_arr=bonds_temp_arr)

compilation -- start

compilation -- done

runs -- start

Running L = 64, T = 1.0, num_steps:10000000.0
Running L = 64, T = 1.1, num_steps:10000000.0
Running L = 64, T = 1.2, num_steps:10000000.0
Running L = 64, T = 1.3, num_steps:10000000.0
Running L = 64, T = 1.4, num_steps:10000000.0
Running L = 64, T = 1.5, num_steps:10000000.0
Running L = 64, T = 1.6, num_steps:10000000.0
Running L = 64, T = 1.7, num_steps:10000000.0
Running L = 64, T = 1.8, num_steps:10000000.0
Running L = 64, T = 1.9, num_steps:10000000.0
Running L = 64, T = 2.0, num_steps:10000000.0
Running L = 64, T = 2.1, num_steps:10000000.0
Running L = 64, T = 2.2, num_steps:10000000.0
Running L = 64, T = 2.3, num_steps:10000000.0
Running L = 64, T = 2.4, num_steps:10000000.0
Running L = 64, T = 2.5, num_steps:10000000.0
Running L = 64, T = 2.6, num_steps:10000000.0
Running L = 64, T = 2.7, num_steps:10000000.0
Running L = 64, T = 2.8, num_steps:10000000.0
Running L = 64, T = 2.9, num_steps:10000000.0
Running L = 64, T = 3.

NameError: name 'start_site' is not defined

In [19]:
t00 = time.time()
for i in range(1):
    t0 = time.time()
    print("\n" + 80*"*" + "\n")
    print("Run #: {0}".format(i))
    print("\n" + 80*"*" + "\n")
    #bonds64 = Bonds(64, run=True, num_steps=1E7, T_arr=bonds_temp_arr_)
    #bonds4 = Bonds(4, run=True, num_steps=1E7, T_arr=bonds4_temp_arr)
    #bonds8 = Bonds(8, run=True, num_steps=1E7, T_arr=bonds8_temp_arr)
    sim4 = WormSimulation(4, run=True, num_steps=1E5, T_arr=bonds4_temp_arr, 
                          bond_flag=0)
    t1 = time.time()
    print("Time for L = 4: {}".format(t1 - t0))
    sim8 = WormSimulation(8, run=True, num_steps=1E7, T_arr=bonds8_temp_arr, 
                          bond_flag=0)
    t2 = time.time()
    print("Time for L = 8: {}".format(t2 - t1))
    #sim16 = WormSimulation(16, run=True, num_steps=1E7, T_arr=bonds16_temp_arr,
    #                       bond_flag=0)
    #t3 = time.time()
    #print("Time for L = 16: {}".format(t3 - t2))
    #sim32 = WormSimulation(32, run=True, num_steps=1E7, T_arr=bonds32_temp_arr,
    #                       bond_flag=0)
    #t4 = time.time()
    #print("Time for L = 32: {}".format(t4 - t3))
    #bonds16 = Bonds(16, run=True, num_steps=1E7, T_arr=bonds_temp_arr_)
    #                bond_stats=False)
    #bonds32 = Bonds(32, run=True, num_steps=1E7, T_arr=bonds_temp_arr_,
    #                bond_stats=False)
    print("Time for 1 run: {}".format(time.time() - t0))
print("Time to complete: {}".format(time.time() - t00))
#~1448s / run
# 13989.77 to complete, generated 113.2-107.1MB for L = 32 observables
# Time for L = 4: 106.37809s
# Time for L = 4: 7.267660s
# Time for L = 32: 31.6713s


********************************************************************************

Run #: 0

********************************************************************************

compilation -- start

compilation -- done

runs -- start

Running L = 4, T = 2.1, num_steps:100000.0
Running L = 4, T = 2.11, num_steps:100000.0
Running L = 4, T = 2.12, num_steps:100000.0
Running L = 4, T = 2.13, num_steps:100000.0
Running L = 4, T = 2.14, num_steps:100000.0
Running L = 4, T = 2.15, num_steps:100000.0
Running L = 4, T = 2.16, num_steps:100000.0
Running L = 4, T = 2.17, num_steps:100000.0
Running L = 4, T = 2.18, num_steps:100000.0
Running L = 4, T = 2.19, num_steps:100000.0
Running L = 4, T = 2.2, num_steps:100000.0
Running L = 4, T = 2.21, num_steps:100000.0
Running L = 4, T = 2.22, num_steps:100000.0
Running L = 4, T = 2.23, num_steps:100000.0
Running L = 4, T = 2.24, num_steps:100000.0
Running L = 4, T = 2.25, num_steps:100000.0
Running L = 4, T = 2.26, num_steps:100000.0
Running L = 4, T = 2.

In [20]:
bonds4 = Bonds(4, run=True, num_steps=1E7, T_arr=bonds4_temps)

compilation -- start

compilation -- done

runs -- start

Running T = 1.0, num_steps: 10000000.0
Running T = 1.1, num_steps: 10000000.0
Running T = 1.2, num_steps: 10000000.0
Running T = 1.3, num_steps: 10000000.0
Running T = 1.4, num_steps: 10000000.0
Running T = 1.5, num_steps: 10000000.0
Running T = 1.6, num_steps: 10000000.0
Running T = 1.7, num_steps: 10000000.0
Running T = 1.8, num_steps: 10000000.0
Running T = 1.8, num_steps: 10000000.0
Running T = 1.85, num_steps: 10000000.0
Running T = 1.9, num_steps: 10000000.0
Running T = 1.9, num_steps: 10000000.0
Running T = 1.95, num_steps: 10000000.0
Running T = 2.0, num_steps: 10000000.0
Running T = 2.0, num_steps: 10000000.0
Running T = 2.05, num_steps: 10000000.0
Running T = 2.1, num_steps: 10000000.0
Running T = 2.1, num_steps: 10000000.0
Running T = 2.15, num_steps: 10000000.0
Running T = 2.2, num_steps: 10000000.0
Running T = 2.2, num_steps: 10000000.0
Running T = 2.25, num_steps: 10000000.0
Running T = 2.3, num_steps: 10000000.0
R

Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_2.9.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_2.95.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_3.0.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_3.1.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_3.2.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_3.3.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_3.4.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_3.5.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_3.6.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_bonds_0/4_config_3.7.txt
Saving blocked configs to: ../data/blocked_configs/4_lattice/double_b

In [7]:
3 % 1

0

In [ ]:
##########################################################
#        Feel free to change parameters as needed        #
##########################################################
for i in range(10):
    print("\n" + 80*"*" + "\n")
    print("Run #: {}".format(i))
    print("\n" + 80*"*" + "\n")
    # run from 1.0 to 3.5 in steps of 0.1
    bonds4 = Bonds(4, run=True, num_steps=1E8)
    bonds8 = Bonds(8, run=True, num_steps=1E8)
    bonds16 = Bonds(16, run=True, num_steps=1E8)
    bonds32 = Bonds(32, run=True, num_steps=1E7)
    # run from 1.8 to 2.8 in steps of 0.05
    bonds32 = Bonds(32, run=True, num_steps=1E8, 
                    T_start=1.8, T_end=2.8, T_step=0.05)
    bonds16 = Bonds(16, run=True, num_steps=1E8, 
                    T_start=1.8, T_end=2.8, T_step=0.05)
    bonds8 = Bonds(8, run=True, num_steps=1E8, 
                   T_start=1.8, T_end=2.8, T_step=0.05)
    bonds4 = Bonds(4, run=True, num_steps=1E8, 
                   T_start=1.8, T_end=2.8, T_step=0.05)